[package]
name = "lcalc"
version = "0.1.0"
authors = ["tomsmeding <tom.smeding@gmail.com>"]
edition = "2018"

[dependencies]
pom = "^3.1"
num-bigint = ""
num-rational = "^0.2.3"
num-traits = "^0.2.11"  # Note: synchronised with the num-bigint dependency
